model_sas:
  embed_size: 50
  shared_embed: true
  dropout: 0.1
  num_blocks: 2

model_caser:
  embed_size: 50
  shared_embed: true
  dropout: 0.1
  num_blocks: 2

dataset:
  path: 'data/Beauty.txt'
  max_len: 50
  n_neg_samples: 1
  batch_size: 128

n_epochs: 200
verbose_loss_every: 0.34
verbose_metrics_every: 0.5
